# Generated by Django 4.2.6 on 2023-10-22 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('cod_cuenta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_cuenta', models.CharField(max_length=50)),
                ('saldo_cuenta', models.FloatField()),
                ('total_debe_c', models.FloatField()),
                ('total_haber_c', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='tipo_cuenta',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_esfinanciero',
            fields=[
                ('id_es', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom_es', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='transaccion',
            fields=[
                ('num_transaccion', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('total_debe_tran', models.FloatField()),
                ('total_haber_tran', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='cuenta_transaccion',
            fields=[
                ('id_ct', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('debe', models.FloatField()),
                ('haber', models.FloatField()),
                ('cod_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomCodeSolutions.cuenta')),
                ('num_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomCodeSolutions.transaccion')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='id_es',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomCodeSolutions.tipo_esfinanciero'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomCodeSolutions.tipo_cuenta'),
        ),
    ]
