# Generated by Django 4.2.6 on 2023-10-22 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=10)),
                ('saldo', models.FloatField()),
                ('total_debe', models.FloatField()),
                ('total_haber', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tiene_cod_cuenta', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('total_debe', models.FloatField()),
                ('total_haber', models.FloatField()),
                ('registra', models.CharField(max_length=500)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomCodeSolutions.cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomCodeSolutions.tipocuenta'),
        ),
    ]
