# Generated by Django 4.2.6 on 2023-10-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomCodeSolutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_cuenta',
            name='nom_tipo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
