# Generated by Django 4.2.6 on 2023-10-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomCodeSolutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costos_Directos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CostosIndirectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mano_de_Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_trabajador', models.CharField(max_length=255)),
                ('tiempo_de_trabajo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_Trabajador', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
