# Generated by Django 4.2.6 on 2023-10-26 17:14

import CustomCodeSolutions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomCodeSolutions', '0002_tipo_cuenta_nom_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costos_Directos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'costos_directos',
            },
        ),
        migrations.CreateModel(
            name='CostosIndirectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'costos_indirectos',
            },
        ),
        migrations.CreateModel(
            name='Mano_de_Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_trabajador', models.CharField(max_length=255)),
                ('tiempo_de_trabajo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_Trabajador', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'mano_de_obra',
            },
        ),
        migrations.CreateModel(
            name='Tabla_Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=15)),
                ('producto', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
                ('costos_directos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mano_de_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costos_indirectos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'tabla_final',
            },
        ),
        migrations.AlterField(
            model_name='cuenta_transaccion',
            name='debe',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cuenta_transaccion',
            name='haber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='num_transaccion',
            field=models.IntegerField(default=CustomCodeSolutions.models.get_default_value, primary_key=True, serialize=False, unique=True),
        ),
    ]
