# Generated by Django 4.2.6 on 2023-10-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomCodeSolutions', '0002_costos_directos_costosindirectos_mano_de_obra'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='costos_directos',
            table='costos_directos',
        ),
        migrations.AlterModelTable(
            name='costosindirectos',
            table='costos_indirectos',
        ),
        migrations.AlterModelTable(
            name='mano_de_obra',
            table='mano_de_obra',
        ),
    ]
